### PR TITLE
Add support for compounding validators and the related withdrawal credentials from EIP 7251

### LINKED ISSUE #227: Add support for EIP 7251 in preparation for Pectra
[EIP-7251: Increase the MAX_EFFECTIVE_BALANCE](https://eips.ethereum.org/EIPS/eip-7251) adds a new withdrawal credentials `0x02` for a compounding validator with 2048 ETH as its max effective balance. We should add support for this in the `new-mnemonic`, `existing-mnemonic` and `partial-deposit` commands.

EIP-7251 is expected to land with the Pectra fork.

### PR DESCRIPTION
**Pull request by remyroy**
**What I did**

- [X] Added an option to the `new-mnemonic`, `existing-mnemonic` and `partial-deposit` commands to use `0x02` withdrawal credentials for compounding validators.
- [X] Added an `amount` option to the `new-mnemonic` and `existing-mnemonic` commands for larger than 32 ETH deposits.
- [x] Updated unit tests and added more unit tests for these new features
- [x] Updated the related documentation for these new features

**Related issue**

Fixes #227

### CODE REVIEW

**Comment by remyroy** [comment]
When entering > 2048, we get a traceback:
```
tive balance. [False]: yes
Please enter the amount you wish to deposit to these validators. Must be at least 1 ether and can not have greater precision than 1 gwei. 32 is required to activate a new validator [32]: 2050
Traceback (most recent call last):
  File "/Users/bbusa/Documents/Ethereum.nosync/testnets/mekong-deposit-test/ethstaker-deposit-cli/ethstaker_deposit/utils/intl.py", line 29, in _get_from_dict
    ans = reduce(dict.get, mapList, dataDict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'NoneType' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bbusa/Documents/Ethereum.nosync/testnets/mekong-deposit-test/ethstaker-deposit-cli/ethstaker_deposit/utils/intl.py", line 73, in load_text
    return _get_from_dict(text_dict, [func] + params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bbusa/Documents/Ethereum.nosync/testnets/mekong-deposit-test/ethstaker-deposit-cli/ethstaker_deposit/utils/intl.py", line 34, in _get_from_dict
    raise KeyError('%s not in internationalisation json file.' % mapList)
KeyError: "['validate_deposit_amount', 'err_max_deposit'] not in internationalisation json file."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/bbusa/Documents/Ethereum.nosync/testnets/mekong-deposit-test/ethstaker-deposit-cli/ethstaker_deposit/__main__.py", line 4, in <module>
    deposit.run()
  File "/Users/bbusa/Documents/Ethereum.nosync/testnets/mekong-deposit-test/ethstaker-deposit-cli/ethstaker_deposit/deposit.py", line 127, in run
    cli()
  File "/Users/bbusa/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bbusa/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/bbusa/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/click/core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bbusa/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/Users/bbusa/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bbusa/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bbusa/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/click/core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bbusa/Documents/Ethereum.nosync/testnets/mekong-deposit-test/ethstaker-deposit-cli/ethstaker_deposit/utils/click.py", line 142, in callback
    processed_input = processing_func(user_input)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bbusa/Documents/Ethereum.nosync/testnets/mekong-deposit-test/ethstaker-deposit-cli/ethstaker_deposit/cli/generate_keys.py", line 132, in <lambda>
    lambda amount: validate_deposit_amount(amount),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bbusa/Documents/Ethereum.nosync/testnets/mekong-deposit-test/ethstaker-deposit-cli/ethstaker_deposit/utils/validation.py", line 217, in validate_deposit_amount
    raise ValidationError(load_text(['err_max_deposit']))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bbusa/Documents/Ethereum.nosync/testnets/mekong-deposit-test/ethstaker-deposit-cli/ethstaker_deposit/utils/intl.py", line 77, in load_text
    raise KeyError('%s not in %s file' % ([func] + params, json_path))
KeyError: "['validate_deposit_amount', 'err_max_deposit'] not in /Users/bbusa/Documents/Ethereum.nosync/testnets/mekong-deposit-test/ethstaker-deposit-cli/ethstaker_deposit/intl/en/utils/validation.json file"
```

**Comment by barnabasbusa** [comment]
Could you please rebase this over latest master?

**Comment by remyroy** [comment]
@barnabasbusa Done

**Review by valefar-on-discord — APPROVED** [review]
Played around with it quite a bit and didn't run into any issues.
The prompting for 0x02 and amount is a very nice.

**Pull request merged**
