### PR TITLE
Fix for setuptools yanked version

### LINKED ISSUE #6: Update the setuptools package
The current version 69.3.0 is a yanked version.
```
WARNING: The candidate selected for download or install is a yanked version: 'setuptools' candidate (version 69.3.0 at https://files.pythonhosted.org/packages/9a/4b/7b8a217633a4eda8fdf06233a38804adf3c281287728daddef031d15b635/setuptools-69.3.0-py3-none-any.whl (from https://pypi.org/simple/setuptools/) (requires-python:>=3.8))
Reason for being yanked: https://github.com/pypa/setuptools/issues/4302
Installing collected packages: cached-property, toolz, six, setuptools, pycryptodome, mypy-extensions, lru-dict, eth-typing, eth-hash, click, pyrsistent, cytoolz, eth-utils, ssz, py-ecc
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.5.0
    Uninstalling setuptools-65.5.0:
      Successfully uninstalled setuptools-65.5.0
```

### PR DESCRIPTION
**Pull request by remyroy**
Fixes #6

### CODE REVIEW

**Comment by remyroy** [comment]
This is related to https://github.com/pypa/setuptools/issues/4302

**Comment by valefar-on-discord** [comment]
Thoughts on this?:
https://pip.pypa.io/en/stable/topics/secure-installs/#do-not-use-setuptools-directly

**Review by valefar-on-discord — APPROVED** [review]
This is a net positive but we might want to investigate not using setuptools given the security concern laid out above, unless I misunderstood.

**Comment by remyroy** [comment]
> Thoughts on this?: https://pip.pypa.io/en/stable/topics/secure-installs#do-not-use-setuptools-directly

Let me explore this in details.

**Comment by remyroy** [comment]
The projects calls *deprecated interfaces* like `python setup.py install` which requires setuptools in https://github.com/eth-educators/ethstaker-deposit-cli/blob/main/deposit.sh#L8 for instance. As long as we have those, we need to have setuptools and a recent version for python 3.12 support.

Eventually, we might want to clean that up. I created #11 about it.

**Pull request merged**
