### PR TITLE
Clear scrollback

### LINKED ISSUE #32: Clipboard or terminal scrollback mnemonic vulnerability
Forward from 
- https://github.com/ethereum/staking-deposit-cli/issues/97

The [2020 Audit of staking-deposit-cli](https://github.com/trailofbits/publications/blob/master/reviews/ETH2DepositCLI.pdf) mentioned a task to properly clear the terminal buffer and clipboard to prevent the possibility of leaking the mnemonic.  This was investigated by Carl and he has concerns around cross-platform solutions.

Ultimately it may not be possible to resolve this for every usecase but something that should be investigated as is a likely output from any future audit.

### PR DESCRIPTION
**Pull request by yorickdowne**
Resolves #32 , together with #130

## Changes

Instead of `click.clear()` use `cls` or `tput reset`, depending on OS. This clears the scrollback of the terminal, at least on "modern" versions of Windows, Linux and macOS

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by yorickdowne** [comment]
I appear to be breaking the new-mnemonic test on Windows with this, though I am unclear how. If the Windows tests don't complete (hang), then I'll need to find a Windows machine to test this PR on

**Comment by remyroy** [comment]
I'll check on my Windows dev machine to see if I can find the issue.

**Comment by remyroy** [comment]
All those tests seem to fail on my system because we are calling `sh deposit.sh` to run the integrated test on Windows and `sh` isn't found. I'm not sure why these tests were created that way but it's likely the wrong way to do it on Windows. We could try to rewrite them with the `click.testing.CliRunner`.

**Comment by yorickdowne** [comment]
Wait but this used to work ….

**Comment by remyroy** [comment]
It might be something else. Let me try to debug this.

**Comment by yorickdowne** [comment]
I am special-casing for asyncio on win32 now, to catch these two tests. I also manually tried `sh deposit.sh` in Git Bash with the way test 8 runs (exact same parameters), and it behaves as I'd expect it to.

**Review by remyroy — APPROVED** [review]
I'm still having some troubles running this on my Windows dev machine sucessfully, but since it works with the test suite now on Github runners and the feature is working on my side so I guess we are good to go.

**Pull request merged**
