### PR TITLE
Add coverage reports to github actions

### PR DESCRIPTION
**Pull request by jshufro**
Uses [coverage.py](https://coverage.readthedocs.io/en/7.6.1/) to produce coverage reports in CI.
Special care is given to avoid the security snafus in [this article](https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/)

`relative_files = True` is required for cross-platform compatibility when merging coverage reports generated by the run matrix.

An html report is generated and uploaded to github (retention 60 days), as well as a text summary.
The text summary and a link to the html report are added to the pull request as a comment.

Screenshots for reference:

image

image

image

image

NB: "comment" workflow file is added in a separate commit since it needs to reside on the target branch (see above link for security explanation)

### CODE REVIEW

**Comment by remyroy** [comment]
I've been reviewing this one for a few hours just so we don't all review it at the same time.

**Comment by remyroy** [comment]
A concret example of this can be found on https://github.com/remyroy/ethstaker-deposit-cli/pull/1

**Comment by remyroy** [comment]
One non-blocking issue for this PR is the fact that the added PR comment will spam notifications (Github notifications, emails, etc) and there is no way to easily disable that notification that I could find. Some [mute feature has been requested](https://github.com/orgs/community/discussions/5793) but it's still ongoing.

**Comment by jshufro** [comment]
> One non-blocking issue for this PR is the fact that the added PR comment will spam notifications (Github notifications, emails, etc) and there is no way to easily disable that notification that I could find. Some [mute feature has been requested](https://github.com/orgs/community/discussions/5793) but it's still ongoing.

There is perhaps a tenable improvement to be made, wherein the previous comment is edited instead of a new comment being posted. I've seen some workflows that can do that.

**Review by remyroy — APPROVED** [review]
This is good enough for me to merge.

**Pull request merged**
